name: report
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fluttertoast: ^3.0.3
  progress_dialog: ^1.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_cupertino_date_picker: ^1.0.12
  flutter_datetime_picker: ^1.2.8
  audioplayers: ^0.10.0
  oktoast: ^2.0.0
  charts_flutter: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_picker:
  git: git://github.com/yangyxd/flutter_picker.git

flutter:

  uses-material-design: true

  fonts:
    - family: GFSDidot
      fonts:
        - asset: fonts/GFSDidot-Regular.ttf
  assets:
    - images/
