name: report
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"



dependencies:
  flutter_calendar_carousel: ^1.4.12
  fluttertoast: ^3.0.3
  progress_dialog: ^1.2.0
  http: ^0.12.0
  intl: ">=0.1.0 <0.17.0"
  flutter_screenutil: ^0.3.0
  flutter:
    sdk: flutter
  camera:
  path:
  path_provider:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_cupertino_date_picker: ^1.0.12
  flutter_datetime_picker: ^1.2.8
  audioplayers: ^0.10.0
  oktoast: ^2.0.0
  charts_flutter: ^0.6.0
  provider: ^3.0.0+1
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_picker:
  git: git://github.com/yangyxd/flutter_picker.git

flutter:

  uses-material-design: true

  fonts:
    - family: GFSDidot
      fonts:
        - asset: fonts/GFSDidot-Regular.ttf
  assets:
    - images/
